package com.iris.scholar.server.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2
 * Tue Apr 28 11:17:33 CST 2009
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://ws.server.scholar.iris.com", name = "IScholarFetchServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface IScholarFetchServicePortType {

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "writeData", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.WriteData")
    @ResponseWrapper(localName = "writeDataResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.WriteDataResponse")
    @WebMethod
    public int writeData(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "getSearchInfo", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetSearchInfo")
    @ResponseWrapper(localName = "getSearchInfoResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetSearchInfoResponse")
    @WebMethod
    public java.lang.String getSearchInfo(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1
    );

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "getSearchStr", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetSearchStr")
    @ResponseWrapper(localName = "getSearchStrResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetSearchStrResponse")
    @WebMethod
    public java.lang.String getSearchStr(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3
    );

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "getRecordsNum", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetRecordsNum")
    @ResponseWrapper(localName = "getRecordsNumResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetRecordsNumResponse")
    @WebMethod
    public int getRecordsNum(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3
    );

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "upLoadOver", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.UpLoadOver")
    @ResponseWrapper(localName = "upLoadOverResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.UpLoadOverResponse")
    @WebMethod
    public boolean upLoadOver(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3
    );

    @RequestWrapper(localName = "writeErrorInfo", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.WriteErrorInfo")
    @ResponseWrapper(localName = "writeErrorInfoResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.WriteErrorInfoResponse")
    @WebMethod
    public void writeErrorInfo(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3,
        @WebParam(name = "in4", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in4
    );

    @WebResult(name = "out", targetNamespace = "http://ws.server.scholar.iris.com")
    @RequestWrapper(localName = "getRecords", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetRecords")
    @ResponseWrapper(localName = "getRecordsResponse", targetNamespace = "http://ws.server.scholar.iris.com", className = "com.iris.scholar.server.ws.GetRecordsResponse")
    @WebMethod
    public java.lang.String getRecords(
        @WebParam(name = "in0", targetNamespace = "http://ws.server.scholar.iris.com")
        java.lang.String in0,
        @WebParam(name = "in1", targetNamespace = "http://ws.server.scholar.iris.com")
        int in1,
        @WebParam(name = "in2", targetNamespace = "http://ws.server.scholar.iris.com")
        int in2,
        @WebParam(name = "in3", targetNamespace = "http://ws.server.scholar.iris.com")
        int in3
    );
}
