package com.toney.istyle.module;

import java.util.Date;

/**
 * 
 *************************************************************** 
 * <p>
 * 
 * @CLASS :IstylePrdPicture
 * @DESCRIPTION :商品的图片Module
 * @AUTHOR :toney.li
 * @VERSION :v1.0
 * @DATE :Mar 10, 2013
 *       </p>
 **************************************************************** 
 */
public class ProductPicModule extends BaseModule {
	/**
	 * 
	 */
	private static final long serialVersionUID = 6532505850864995229L;
	private Long parentId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.ID
	 * 
	 * 
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.PID
	 * 
	 * 
	 */
	private String pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.WIDTH
	 * 
	 * 
	 */
	private Short width;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.HEIGHT
	 * 
	 * 
	 */
	private Short height;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.URL
	 * 
	 * 
	 */
	private String url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.CREATE_DATE
	 * 
	 * 
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRD_PICTURE.PIC_TYPE
	 * 
	 * 
	 */
	private String picType;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.ID
	 * 
	 * @return the value of T_PRD_PICTURE.ID
	 * 
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.ID
	 * 
	 * @param id
	 *            the value for T_PRD_PICTURE.ID
	 * 
	 * 
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.PID
	 * 
	 * @return the value of T_PRD_PICTURE.PID
	 * 
	 * 
	 */
	public String getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.PID
	 * 
	 * @param pid
	 *            the value for T_PRD_PICTURE.PID
	 * 
	 * 
	 */
	public void setPid(String pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.WIDTH
	 * 
	 * @return the value of T_PRD_PICTURE.WIDTH
	 * 
	 * 
	 */
	public Short getWidth() {
		return width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.WIDTH
	 * 
	 * @param width
	 *            the value for T_PRD_PICTURE.WIDTH
	 * 
	 * 
	 */
	public void setWidth(Short width) {
		this.width = width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.HEIGHT
	 * 
	 * @return the value of T_PRD_PICTURE.HEIGHT
	 * 
	 * 
	 */
	public Short getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.HEIGHT
	 * 
	 * @param height
	 *            the value for T_PRD_PICTURE.HEIGHT
	 * 
	 * 
	 */
	public void setHeight(Short height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.URL
	 * 
	 * @return the value of T_PRD_PICTURE.URL
	 * 
	 * 
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.URL
	 * 
	 * @param url
	 *            the value for T_PRD_PICTURE.URL
	 * 
	 * 
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.CREATE_DATE
	 * 
	 * @return the value of T_PRD_PICTURE.CREATE_DATE
	 * 
	 * 
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for T_PRD_PICTURE.CREATE_DATE
	 * 
	 * 
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRD_PICTURE.PIC_TYPE
	 * 
	 * @return the value of T_PRD_PICTURE.PIC_TYPE
	 * 
	 * 
	 */
	public String getPicType() {
		return picType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRD_PICTURE.PIC_TYPE
	 * 
	 * @param picType
	 *            the value for T_PRD_PICTURE.PIC_TYPE
	 * 
	 * 
	 */
	public void setPicType(String picType) {
		this.picType = picType;
	}

	public Long getParentId() {
		return parentId;
	}

	public void setParentId(Long parentId) {
		this.parentId = parentId;
	}

	@Override
	public String toString() {
		return "ProductPicModule [parentId=" + parentId + ", id=" + id + ", pid=" + pid + ", width=" + width + ", height=" + height + ", url=" + url + ", createDate=" + createDate
				+ ", picType=" + picType + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result + ((height == null) ? 0 : height.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((parentId == null) ? 0 : parentId.hashCode());
		result = prime * result + ((picType == null) ? 0 : picType.hashCode());
		result = prime * result + ((pid == null) ? 0 : pid.hashCode());
		result = prime * result + ((url == null) ? 0 : url.hashCode());
		result = prime * result + ((width == null) ? 0 : width.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductPicModule other = (ProductPicModule) obj;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (height == null) {
			if (other.height != null)
				return false;
		} else if (!height.equals(other.height))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (parentId == null) {
			if (other.parentId != null)
				return false;
		} else if (!parentId.equals(other.parentId))
			return false;
		if (picType == null) {
			if (other.picType != null)
				return false;
		} else if (!picType.equals(other.picType))
			return false;
		if (pid == null) {
			if (other.pid != null)
				return false;
		} else if (!pid.equals(other.pid))
			return false;
		if (url == null) {
			if (other.url != null)
				return false;
		} else if (!url.equals(other.url))
			return false;
		if (width == null) {
			if (other.width != null)
				return false;
		} else if (!width.equals(other.width))
			return false;
		return true;
	}

}