package com.toney.istyle.module;

import java.util.Date;

import com.toney.istyle.commons.BaseObject;

/**
 * 
 *************************************************************** 
 * <p>
 * 
 * @CLASS :IstyleProductModule
 * @DESCRIPTION :商品信息
 * @AUTHOR :toney.li
 * @VERSION :v1.0
 * @DATE :Mar 10, 2013
 *       </p>
 **************************************************************** 
 */
public class ProductModule extends BaseObject {
	/**
	 * 
	 */
	private static final long serialVersionUID = 4425951237740758702L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.ID
	 * 
	 * 
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.PRODUCE_CODE
	 * 
	 * 
	 */
	private String produceCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.PLATFORM_CODE
	 * 
	 * 
	 */
	private String platformCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.PRODUCT_NAME
	 * 
	 * 
	 */
	private String productName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.ONSALE
	 * 
	 * 
	 */
	private Short onsale;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.UPLOAD_UID
	 * 
	 * 
	 */
	private Long uploadUid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.LAST_UPDATE
	 * 
	 * 
	 */
	private Date lastUpdate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.CREATE_DATE
	 * 
	 * 
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_PRODUCT.STATUS
	 * 
	 * 
	 */
	private Short status;

	/**
	 * 商品的URL
	 */
	private String productUrl;

	/**
	 * 类目
	 */
	private Integer catCode;

	private Integer cityId;
	private String description;

	public Integer getCityId() {
		return cityId;
	}

	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getCatCode() {
		return catCode;
	}

	public void setCatCode(Integer catCode) {
		this.catCode = catCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.productUrl
	 * 
	 * @return the value of T_PRODUCT.productUrl
	 * 
	 * 
	 */
	public String getProductUrl() {
		return productUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.productUrl
	 * 
	 * @param the
	 *            value of T_PRODUCT.productUrl
	 * 
	 * 
	 */
	public void setProductUrl(String productUrl) {
		this.productUrl = productUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.ID
	 * 
	 * @return the value of T_PRODUCT.ID
	 * 
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.ID
	 * 
	 * @param id
	 *            the value for T_PRODUCT.ID
	 * 
	 * 
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.PRODUCE_CODE
	 * 
	 * @return the value of T_PRODUCT.PRODUCE_CODE
	 * 
	 * 
	 */
	public String getProduceCode() {
		return produceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.PRODUCE_CODE
	 * 
	 * @param produceCode
	 *            the value for T_PRODUCT.PRODUCE_CODE
	 * 
	 * 
	 */
	public void setProduceCode(String produceCode) {
		this.produceCode = produceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.PLATFORM_CODE
	 * 
	 * @return the value of T_PRODUCT.PLATFORM_CODE
	 * 
	 * 
	 */
	public String getPlatformCode() {
		return platformCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.PLATFORM_CODE
	 * 
	 * @param platformCode
	 *            the value for T_PRODUCT.PLATFORM_CODE
	 * 
	 * 
	 */
	public void setPlatformCode(String platformCode) {
		this.platformCode = platformCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.PRODUCT_NAME
	 * 
	 * @return the value of T_PRODUCT.PRODUCT_NAME
	 * 
	 * 
	 */
	public String getProductName() {
		return productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.PRODUCT_NAME
	 * 
	 * @param productName
	 *            the value for T_PRODUCT.PRODUCT_NAME
	 * 
	 * 
	 */
	public void setProductName(String productName) {
		this.productName = productName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.ONSALE
	 * 
	 * @return the value of T_PRODUCT.ONSALE
	 * 
	 * 
	 */
	public Short getOnsale() {
		return onsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.ONSALE
	 * 
	 * @param onsale
	 *            the value for T_PRODUCT.ONSALE
	 * 
	 * 
	 */
	public void setOnsale(Short onsale) {
		this.onsale = onsale;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.UPLOAD_UID
	 * 
	 * @return the value of T_PRODUCT.UPLOAD_UID
	 * 
	 * 
	 */
	public Long getUploadUid() {
		return uploadUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.UPLOAD_UID
	 * 
	 * @param uploadUid
	 *            the value for T_PRODUCT.UPLOAD_UID
	 * 
	 * 
	 */
	public void setUploadUid(Long uploadUid) {
		this.uploadUid = uploadUid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.LAST_UPDATE
	 * 
	 * @return the value of T_PRODUCT.LAST_UPDATE
	 * 
	 * 
	 */
	public Date getLastUpdate() {
		return lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.LAST_UPDATE
	 * 
	 * @param lastUpdate
	 *            the value for T_PRODUCT.LAST_UPDATE
	 * 
	 * 
	 */
	public void setLastUpdate(Date lastUpdate) {
		this.lastUpdate = lastUpdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.CREATE_DATE
	 * 
	 * @return the value of T_PRODUCT.CREATE_DATE
	 * 
	 * 
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for T_PRODUCT.CREATE_DATE
	 * 
	 * 
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_PRODUCT.STATUS
	 * 
	 * @return the value of T_PRODUCT.STATUS
	 * 
	 * 
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_PRODUCT.STATUS
	 * 
	 * @param status
	 *            the value for T_PRODUCT.STATUS
	 * 
	 * 
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "ProductModule [id=" + id + ", produceCode=" + produceCode + ", platformCode=" + platformCode + ", productName=" + productName + ", onsale=" + onsale
				+ ", uploadUid=" + uploadUid + ", lastUpdate=" + lastUpdate + ", createDate=" + createDate + ", status=" + status + ", productUrl=" + productUrl + ", catCode="
				+ catCode + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((catCode == null) ? 0 : catCode.hashCode());
		result = prime * result + ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((lastUpdate == null) ? 0 : lastUpdate.hashCode());
		result = prime * result + ((onsale == null) ? 0 : onsale.hashCode());
		result = prime * result + ((platformCode == null) ? 0 : platformCode.hashCode());
		result = prime * result + ((produceCode == null) ? 0 : produceCode.hashCode());
		result = prime * result + ((productName == null) ? 0 : productName.hashCode());
		result = prime * result + ((productUrl == null) ? 0 : productUrl.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((uploadUid == null) ? 0 : uploadUid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ProductModule other = (ProductModule) obj;
		if (catCode == null) {
			if (other.catCode != null)
				return false;
		} else if (!catCode.equals(other.catCode))
			return false;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (lastUpdate == null) {
			if (other.lastUpdate != null)
				return false;
		} else if (!lastUpdate.equals(other.lastUpdate))
			return false;
		if (onsale == null) {
			if (other.onsale != null)
				return false;
		} else if (!onsale.equals(other.onsale))
			return false;
		if (platformCode == null) {
			if (other.platformCode != null)
				return false;
		} else if (!platformCode.equals(other.platformCode))
			return false;
		if (produceCode == null) {
			if (other.produceCode != null)
				return false;
		} else if (!produceCode.equals(other.produceCode))
			return false;
		if (productName == null) {
			if (other.productName != null)
				return false;
		} else if (!productName.equals(other.productName))
			return false;
		if (productUrl == null) {
			if (other.productUrl != null)
				return false;
		} else if (!productUrl.equals(other.productUrl))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (uploadUid == null) {
			if (other.uploadUid != null)
				return false;
		} else if (!uploadUid.equals(other.uploadUid))
			return false;
		return true;
	}

}