package com.toney.istyle.module;

import java.util.Date;

import com.toney.istyle.commons.BaseObject;

/**
 * 
 *************************************************************** 
 * <p>
 * 
 * @CLASS :IstyleUserModule
 * @DESCRIPTION :用户信息
 * @AUTHOR :toney.li
 * @VERSION :v1.0
 * @DATE :Mar 10, 2013
 *       </p>
 **************************************************************** 
 */
public class UserModule extends BaseObject {
	/**
	 * 
	 */
	private static final long serialVersionUID = 2104977300763669265L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.ID
	 * 
	 * 
	 */
	private Long id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.USER_NAME
	 * 
	 * 
	 */
	private String userName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.PASSWORD
	 * 
	 * 
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.NICK_NAME
	 * 
	 * 
	 */
	private Long nickName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.MOBILE
	 * 
	 * 
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.CREATE_DATE
	 * 
	 * 
	 */
	private Date createDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER.STATUS
	 * 
	 * 
	 */
	private Short status;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.ID
	 * 
	 * @return the value of T_USER.ID
	 * 
	 * 
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.ID
	 * 
	 * @param id
	 *            the value for T_USER.ID
	 * 
	 * 
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.USER_NAME
	 * 
	 * @return the value of T_USER.USER_NAME
	 * 
	 * 
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.USER_NAME
	 * 
	 * @param userName
	 *            the value for T_USER.USER_NAME
	 * 
	 * 
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.PASSWORD
	 * 
	 * @return the value of T_USER.PASSWORD
	 * 
	 * 
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.PASSWORD
	 * 
	 * @param password
	 *            the value for T_USER.PASSWORD
	 * 
	 * 
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.NICK_NAME
	 * 
	 * @return the value of T_USER.NICK_NAME
	 * 
	 * 
	 */
	public Long getNickName() {
		return nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.NICK_NAME
	 * 
	 * @param nickName
	 *            the value for T_USER.NICK_NAME
	 * 
	 * 
	 */
	public void setNickName(Long nickName) {
		this.nickName = nickName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.MOBILE
	 * 
	 * @return the value of T_USER.MOBILE
	 * 
	 * 
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.MOBILE
	 * 
	 * @param mobile
	 *            the value for T_USER.MOBILE
	 * 
	 * 
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.CREATE_DATE
	 * 
	 * @return the value of T_USER.CREATE_DATE
	 * 
	 * 
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.CREATE_DATE
	 * 
	 * @param createDate
	 *            the value for T_USER.CREATE_DATE
	 * 
	 * 
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER.STATUS
	 * 
	 * @return the value of T_USER.STATUS
	 * 
	 * 
	 */
	public Short getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER.STATUS
	 * 
	 * @param status
	 *            the value for T_USER.STATUS
	 * 
	 * 
	 */
	public void setStatus(Short status) {
		this.status = status;
	}

	@Override
	public String toString() {
		return "UserModule [id=" + id + ", userName=" + userName + ", password=" + password + ", nickName=" + nickName + ", mobile=" + mobile + ", createDate=" + createDate
				+ ", status=" + status + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((createDate == null) ? 0 : createDate.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((mobile == null) ? 0 : mobile.hashCode());
		result = prime * result + ((nickName == null) ? 0 : nickName.hashCode());
		result = prime * result + ((password == null) ? 0 : password.hashCode());
		result = prime * result + ((status == null) ? 0 : status.hashCode());
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserModule other = (UserModule) obj;
		if (createDate == null) {
			if (other.createDate != null)
				return false;
		} else if (!createDate.equals(other.createDate))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (mobile == null) {
			if (other.mobile != null)
				return false;
		} else if (!mobile.equals(other.mobile))
			return false;
		if (nickName == null) {
			if (other.nickName != null)
				return false;
		} else if (!nickName.equals(other.nickName))
			return false;
		if (password == null) {
			if (other.password != null)
				return false;
		} else if (!password.equals(other.password))
			return false;
		if (status == null) {
			if (other.status != null)
				return false;
		} else if (!status.equals(other.status))
			return false;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		return true;
	}

}