package com.toney.istyle.module;

import java.util.Date;

import com.toney.istyle.commons.BaseObject;

public class UserLoginModule extends BaseObject {
	/**
	 * 
	 */
	private static final long serialVersionUID = 338004245921445502L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER_LOGIN.UID
	 * 
	 * 
	 */
	private Long uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER_LOGIN.LOGIN_DATE
	 * 
	 * 
	 */
	private Date loginDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER_LOGIN.LAST_LOGIN_DATE
	 * 
	 * 
	 */
	private Date lastLoginDate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column T_USER_LOGIN.LOGIN_INFO
	 * 
	 * 
	 */
	private String loginInfo;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER_LOGIN.UID
	 * 
	 * @return the value of T_USER_LOGIN.UID
	 * 
	 * 
	 */
	public Long getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER_LOGIN.UID
	 * 
	 * @param uid
	 *            the value for T_USER_LOGIN.UID
	 * 
	 * 
	 */
	public void setUid(Long uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER_LOGIN.LOGIN_DATE
	 * 
	 * @return the value of T_USER_LOGIN.LOGIN_DATE
	 * 
	 * 
	 */
	public Date getLoginDate() {
		return loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER_LOGIN.LOGIN_DATE
	 * 
	 * @param loginDate
	 *            the value for T_USER_LOGIN.LOGIN_DATE
	 * 
	 * 
	 */
	public void setLoginDate(Date loginDate) {
		this.loginDate = loginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER_LOGIN.LAST_LOGIN_DATE
	 * 
	 * @return the value of T_USER_LOGIN.LAST_LOGIN_DATE
	 * 
	 * 
	 */
	public Date getLastLoginDate() {
		return lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER_LOGIN.LAST_LOGIN_DATE
	 * 
	 * @param lastLoginDate
	 *            the value for T_USER_LOGIN.LAST_LOGIN_DATE
	 * 
	 * 
	 */
	public void setLastLoginDate(Date lastLoginDate) {
		this.lastLoginDate = lastLoginDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column T_USER_LOGIN.LOGIN_INFO
	 * 
	 * @return the value of T_USER_LOGIN.LOGIN_INFO
	 * 
	 * 
	 */
	public String getLoginInfo() {
		return loginInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column T_USER_LOGIN.LOGIN_INFO
	 * 
	 * @param loginInfo
	 *            the value for T_USER_LOGIN.LOGIN_INFO
	 * 
	 * 
	 */
	public void setLoginInfo(String loginInfo) {
		this.loginInfo = loginInfo;
	}

	@Override
	public String toString() {
		return "UserLoginModule [uid=" + uid + ", loginDate=" + loginDate + ", lastLoginDate=" + lastLoginDate + ", loginInfo=" + loginInfo + "]";
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((lastLoginDate == null) ? 0 : lastLoginDate.hashCode());
		result = prime * result + ((loginDate == null) ? 0 : loginDate.hashCode());
		result = prime * result + ((loginInfo == null) ? 0 : loginInfo.hashCode());
		result = prime * result + ((uid == null) ? 0 : uid.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserLoginModule other = (UserLoginModule) obj;
		if (lastLoginDate == null) {
			if (other.lastLoginDate != null)
				return false;
		} else if (!lastLoginDate.equals(other.lastLoginDate))
			return false;
		if (loginDate == null) {
			if (other.loginDate != null)
				return false;
		} else if (!loginDate.equals(other.loginDate))
			return false;
		if (loginInfo == null) {
			if (other.loginInfo != null)
				return false;
		} else if (!loginInfo.equals(other.loginInfo))
			return false;
		if (uid == null) {
			if (other.uid != null)
				return false;
		} else if (!uid.equals(other.uid))
			return false;
		return true;
	}

}