<?php
$z[0]=Array("global","",110,137);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",139,165);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",384,412);
$z[2][4]['name']="cfg_memberurl";
$z[3]=Array("global","",467,492);
$z[3][4]['name']="cfg_cmsurl";
$z[4]=Array("global","",555,581);
$z[4][4]['name']="cfg_dataurl";
$z[5]=Array("global","",649,675);
$z[5][4]['name']="cfg_dataurl";
$z[6]=Array("global","",888,915);
$z[6][4]['name']="cfg_indexurl";
$z[7]=Array("channel","\r\n          <li><a href='[field:typeurl/]'>[field:typename/]</a></li>",943,1131);
$z[7][4]['type']="top";
$z[7][4]['currentstyle']="<li class='thisclass'><a href='~typelink~'>~typename~</a> </li>";
$z[8]=Array("field","",1272,1299);
$z[8][4]['name']="phpurl";
$z[9]=Array("tag","<li><a href='[field:link/]'>[field:tag /]</a></li>\r\n          ",1986,2101);
$z[9][4]['row']="8";
$z[9][4]['getall']="1";
$z[9][4]['sort']="month";

?>