<?php
if(!isset($GLOBALS['_vars'])) $GLOBALS['_vars'] = array(); 
$fields = array();
?><div class="footer w960 center mt1 clear">
<script src="/ad/footerad.js"></script>
<p class="powered">
本站大部分作品收集于网络,仅供原创作者, 读者学习,版权归作者或出版社所有，如有不妥，请来信告知，我们将在24小时之内进行处理。
Copyright ? 2009 91zw.cn All Rights Reserved  <a href='http://www.91zw.cn' target='_blank'>www.91zw.cn</a> 版权所有 
</p>
<script src="http://s80.cnzz.com/stat.php?id=1557341&web_id=1557341" language="JavaScript" charset="gb2312"></script>
<script src="/ad/stat.js"></script>
</div>