<?php
$z[0]=Array("global","",255,281);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",312,341);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",492,517);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",520,546);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("field","",613,640);
$z[4][4]['name']="phpurl";
$z[5]=Array("global","",1382,1407);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1511,1540);
$z[6][4]['name']="keyword";
$z[7]=Array("list","\r\n\r\n	<div class=\"item\">\r\n		<h3><a href=\"[field:arcurl/]\" target=\"_blank\">[field:title/]</a></h3>\r\n		<p class=\"intro\">[field:description/]...</p>\r\n		<p class=\"info\">\r\n			<small>分类：</small><span> <a href=\"[field:typeurl/]\" target=\"_blank\">[field:typename/]</a></span>\r\n			<small>点击：</small><span> [field:click/]</span>\r\n			<small>日期：</small><span> [field:stime/]</span>\r\n		</p>\r\n        <p><span><a href=\"[field:arcurl/]\" target=\"_blank\">[field:arcurl/]</a></span></p>\r\n	</div>\r\n",1604,2143);
$z[7][4]['perpage']="20";
$z[7][4]['bookpage']="LIST";
$z[8]=Array("pagelist","",2213,2242);
$z[8][4]['listsize']="5";
$z[9]=Array("likewords","",2336,2361);
$z[9][4]['num']="8";

?>