package com.toney.dal.dao.generator;

import com.toney.dal.model.generator.AdminAuthMapping;
import com.toney.dal.model.generator.AdminAuthMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminAuthMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int countByExample(AdminAuthMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int deleteByExample(AdminAuthMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int insert(AdminAuthMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int insertSelective(AdminAuthMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    List<AdminAuthMapping> selectByExample(AdminAuthMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    AdminAuthMapping selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") AdminAuthMapping record, @Param("example") AdminAuthMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByExample(@Param("record") AdminAuthMapping record, @Param("example") AdminAuthMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByPrimaryKeySelective(AdminAuthMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_auth
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByPrimaryKey(AdminAuthMapping record);
}