package com.toney.dal.dao.generator;

import com.toney.dal.model.generator.AdminGroupMapping;
import com.toney.dal.model.generator.AdminGroupMappingExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AdminGroupMappingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int countByExample(AdminGroupMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int deleteByExample(AdminGroupMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int deleteByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int insert(AdminGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int insertSelective(AdminGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    List<AdminGroupMapping> selectByExample(AdminGroupMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    AdminGroupMapping selectByPrimaryKey(Short id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByExampleSelective(@Param("record") AdminGroupMapping record, @Param("example") AdminGroupMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByExample(@Param("record") AdminGroupMapping record, @Param("example") AdminGroupMappingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByPrimaryKeySelective(AdminGroupMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin_group
     *
     * @mbggenerated Tue Jul 02 10:47:25 CST 2013
     */
    int updateByPrimaryKey(AdminGroupMapping record);
}