package com.toney.dal.dao.generator;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdminDao {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int countByExample(AdminModel example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int deleteByExample(AdminModel example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int insert(AdminMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int insertSelective(AdminMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	List<AdminMapping> selectByExample(AdminModel example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	AdminMapping selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int updateByExampleSelective(@Param("record") AdminMapping record,
			@Param("example") AdminModel example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int updateByExample(@Param("record") AdminMapping record,
			@Param("example") AdminModel example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int updateByPrimaryKeySelective(AdminMapping record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_admin
	 * 
	 * @mbggenerated Tue Jul 02 10:47:25 CST 2013
	 */
	int updateByPrimaryKey(AdminMapping record);
}