
@rem 请将Java_Home修改为你自己对应的JDK安装目录名
set Java_Home=D:\j2sdk1.4.2_12
set path=%java_home%/bin
set local_home=D:\shinyapp
set classpath=.;%local_home%\lib;
set libpath=.;D:\shinyapp\cmpp3.0\classes;.\lib\jaxrpc.jar;.\lib\axis.jar;.\lib\axis-ant.jar;.\lib\wsdl4j.jar;.\lib\commons-logging.jar;.\lib\commons-discovery.jar;.\lib\log4j-1.2.11.jar;.\lib\scheduling.jar;.\lib\calendrica.jar;.\lib\YZWebService.jar;.\lib\avalon-excalibur-4.1.jar;.\lib\avalon-framework-4.1.5.jar;.\lib\avalon-framework-api-4.1.5.jar;.\lib\avalon-framework-impl-4.1.5.jar;.\lib\RPDBPool.jar;.\lib\Flight.jar;.\lib\unittest.jar;.\lib\mail.jar;.\lib\activation.jar;.\lib\ojdbc14.jar;.\lib\RCNetClient.jar;.\lib\RCNet.jar;.\lib\TrainServer.jar;.\lib\SynServer.jar;.\lib\LEDClient.jar;.\lib\UnicomFreeMT.jar;%Java_Home%\lib\rt.jar;%Java_Home%\lib\tools.jar
set config=-DCMPP_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\cmpp.config -Djava.rmi.server.codebase=file:///D:/shinyapp/cmpp3.0/classes/   -Djava.security.policy=file:D:\shinyapp\cmpp3.0\config\cmpp.policy  -DSERVICE_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\services.xml -DLOG_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\log.config -DDB_POOL_CONFIG=D:/shinyapp/cmpp3.0/config/dbpool.config -DMAILINFO=D:/shinyapp/cmpp3.0/config/mailinfo.config -DQUNFA_CONFIG_FILE=d:/shinyapp/cmpp3.0/config/qunfa.config -DSEND_CAIPU=d:/shinyapp/cmpp3.0/config/time.config
echo java -classpath "%libpath%" %config% -jar  bin\SPService.jar
@rem "D:\shinyapp\cmpp3.0\classes;C:\JBuilder2005\lib\saaj.jar;C:\JBuilder2005\lib\jaxrpc.jar;C:\JBuilder2005\lib\axis.jar;C:\JBuilder2005\lib\axis-ant.jar;C:\JBuilder2005\lib\wsdl4j.jar;C:\JBuilder2005\lib\commons-logging.jar;C:\JBuilder2005\lib\commons-discovery.jar;D:\public-lib\log4j-1.2.11.jar;D:\public-lib\scheduling.jar;D:\public-lib\calendrica.jar;D:\public-lib\YZWebService.jar;D:\public-lib\avalon-excalibur-4.1.jar;D:\public-lib\avalon-framework-4.1.5.jar;D:\public-lib\avalon-framework-api-4.1.5.jar;D:\public-lib\avalon-framework-impl-4.1.5.jar;D:\public-lib\RPDBPool.jar;D:\public-lib\Flight.jar;C:\JBuilder2005\thirdparty\junit3.8\junit.jar;C:\JBuilder2005\lib\unittest.jar;C:\JBuilder2005\lib\mail.jar;C:\JBuilder2005\lib\activation.jar;D:\public-lib\ojdbc14.jar;D:\public-lib\RCNetClient.jar;D:\public-lib\RCNet.jar;D:\public-lib\TrainServer.jar;D:\public-lib\SynServer.jar;D:\public-lib\LEDClient.jar;D:\public-lib\UnicomFreeMT.jar;C:\JBuilder2005\jdk1.4\jre\javaws\javaws.jar;C:\JBuilder2005\jdk1.4\jre\lib\charsets.jar;C:\JBuilder2005\jdk1.4\jre\lib\ext\dnsns.jar;C:\JBuilder2005\jdk1.4\jre\lib\ext\ldapsec.jar;C:\JBuilder2005\jdk1.4\jre\lib\ext\localedata.jar;C:\JBuilder2005\jdk1.4\jre\lib\ext\sunjce_provider.jar;C:\JBuilder2005\jdk1.4\jre\lib\im\indicim.jar;C:\JBuilder2005\jdk1.4\jre\lib\im\thaiim.jar;C:\JBuilder2005\jdk1.4\jre\lib\jce.jar;C:\JBuilder2005\jdk1.4\jre\lib\jsse.jar;C:\JBuilder2005\jdk1.4\jre\lib\plugin.jar;C:\JBuilder2005\jdk1.4\jre\lib\rt.jar;C:\JBuilder2005\jdk1.4\jre\lib\sunrsasign.jar;C:\JBuilder2005\jdk1.4\lib\dt.jar;C:\JBuilder2005\jdk1.4\lib\htmlconverter.jar;C:\JBuilder2005\jdk1.4\lib\tools.jar;C:\JBuilder2005\jdk1.4\SHOCK.jar"  -DCMPP_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\cmpp.config -Djava.rmi.server.codebase=file:///D:/shinyapp/cmpp3.0/classes/   -Djava.security.policy=file:D:\shinyapp\cmpp3.0\config\cmpp.policy  -DSERVICE_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\services.xml -DLOG_CONFIG_FILE=D:\shinyapp\cmpp3.0\config\log.config -DDB_POOL_CONFIG=D:/shinyapp/cmpp3.0/config/dbpool.config -DMAILINFO=D:/shinyapp/cmpp3.0/config/mailinfo.config -DQUNFA_CONFIG_FILE=d:/shinyapp/cmpp3.0/config/qunfa.config -DSEND_CAIPU=d:/shinyapp/cmpp3.0/config/time.config
javaw -classpath "D:\shinyapp\cmpp3.0\classes;%libpath%" %config%  com.ShiningTek.BizService.Master
