package com.toney.crawler.biz;

import org.junit.Test;

import com.toney.crawler.biz.impl.CrawlerBizManagerTest;
import com.toney.crawler.pool.ThreadPoolService;

public class CrawlerBizManagerTestCase {
	@Test
	public void testCrawler(){
		
		ThreadPoolService service=new ThreadPoolService();
		CrawlerBizManagerTest test1=new CrawlerBizManagerTest();
		service.putTask(test1);
	}
	
	public static void main(String[] args) {
		ThreadPoolService service=new ThreadPoolService();
		CrawlerBizManagerTest test1=new CrawlerBizManagerTest();
		test1.setId("1");
		CrawlerBizManagerTest test2=new CrawlerBizManagerTest();
		test2.setId("2");
		CrawlerBizManagerTest test3=new CrawlerBizManagerTest();
		test3.setId("3");
		CrawlerBizManagerTest test4=new CrawlerBizManagerTest();
		test4.setId("4");
		CrawlerBizManagerTest test5=new CrawlerBizManagerTest();
		test5.setId("5");
		CrawlerBizManagerTest test6=new CrawlerBizManagerTest();
		test6.setId("6");
		CrawlerBizManagerTest test7=new CrawlerBizManagerTest();
		test7.setId("7");
		CrawlerBizManagerTest test8=new CrawlerBizManagerTest();
		test8.setId("8");
		CrawlerBizManagerTest test9=new CrawlerBizManagerTest();
		test9.setId("9");
		CrawlerBizManagerTest test10=new CrawlerBizManagerTest();
		test10.setId("10");
		CrawlerBizManagerTest test11=new CrawlerBizManagerTest();
		test11.setId("11");
		CrawlerBizManagerTest test12=new CrawlerBizManagerTest();
		test12.setId("12");
		CrawlerBizManagerTest test13=new CrawlerBizManagerTest();
		test13.setId("13");
		CrawlerBizManagerTest test14=new CrawlerBizManagerTest();
		test14.setId("14");
		CrawlerBizManagerTest test15=new CrawlerBizManagerTest();
		test15.setId("15");
		CrawlerBizManagerTest test16=new CrawlerBizManagerTest();
		test16.setId("16");
		CrawlerBizManagerTest test17=new CrawlerBizManagerTest();
		test17.setId("17");
		CrawlerBizManagerTest test18=new CrawlerBizManagerTest();
		test18.setId("18");
		CrawlerBizManagerTest test19=new CrawlerBizManagerTest();
		test19.setId("19");
		CrawlerBizManagerTest test20=new CrawlerBizManagerTest();
		test20.setId("20");
		CrawlerBizManagerTest test21=new CrawlerBizManagerTest();
		test21.setId("21");
		CrawlerBizManagerTest test22=new CrawlerBizManagerTest();
		test22.setId("22");
		CrawlerBizManagerTest test23=new CrawlerBizManagerTest();
		test23.setId("23");
		CrawlerBizManagerTest test24=new CrawlerBizManagerTest();
		test24.setId("24");
		CrawlerBizManagerTest test25=new CrawlerBizManagerTest();
		test25.setId("25");
		CrawlerBizManagerTest test26=new CrawlerBizManagerTest();
		test26.setId("26");
		CrawlerBizManagerTest test27=new CrawlerBizManagerTest();
		test27.setId("27");
		CrawlerBizManagerTest test28=new CrawlerBizManagerTest();
		test28.setId("28");
		CrawlerBizManagerTest test29=new CrawlerBizManagerTest();
		test29.setId("29");
		CrawlerBizManagerTest test30=new CrawlerBizManagerTest();
		test30.setId("30");
		CrawlerBizManagerTest test31=new CrawlerBizManagerTest();
		test31.setId("31");
		CrawlerBizManagerTest test32=new CrawlerBizManagerTest();
		test32.setId("32");
		CrawlerBizManagerTest test33=new CrawlerBizManagerTest();
		test33.setId("33");
		CrawlerBizManagerTest test34=new CrawlerBizManagerTest();
		test34.setId("34");
		CrawlerBizManagerTest test35=new CrawlerBizManagerTest();
		test35.setId("35");
		CrawlerBizManagerTest test36=new CrawlerBizManagerTest();
		test36.setId("36");
		CrawlerBizManagerTest test37=new CrawlerBizManagerTest();
		test37.setId("37");
		CrawlerBizManagerTest test38=new CrawlerBizManagerTest();
		test38.setId("38");
		CrawlerBizManagerTest test39=new CrawlerBizManagerTest();
		test39.setId("39");
		CrawlerBizManagerTest test40=new CrawlerBizManagerTest();
		test40.setId("40");
		CrawlerBizManagerTest test41=new CrawlerBizManagerTest();
		test41.setId("41");
		CrawlerBizManagerTest test42=new CrawlerBizManagerTest();
		test42.setId("42");
		CrawlerBizManagerTest test43=new CrawlerBizManagerTest();
		test43.setId("43");
		CrawlerBizManagerTest test44=new CrawlerBizManagerTest();
		test44.setId("44");
		CrawlerBizManagerTest test45=new CrawlerBizManagerTest();
		test45.setId("45");
		service.putTask(test1);
		service.putTask(test2);
		service.putTask(test3);
		service.putTask(test4);
		service.putTask(test5);
		service.putTask(test6);
		service.putTask(test7);
		service.putTask(test8);
		service.putTask(test9);
		service.putTask(test10);
		service.putTask(test11);
		service.putTask(test12);
		service.putTask(test13);
		service.putTask(test14);
		service.putTask(test15);
		service.putTask(test16);
		service.putTask(test17);
		service.putTask(test18);
		service.putTask(test19);
		service.putTask(test20);
		service.putTask(test21);
		service.putTask(test22);
		service.putTask(test23);
		service.putTask(test24);
		service.putTask(test25);
		service.putTask(test26);
		service.putTask(test27);
		service.putTask(test28);
		service.putTask(test29);
		service.putTask(test30);
		service.putTask(test31);
		service.putTask(test32);
		service.putTask(test33);
		service.putTask(test34);
		service.putTask(test35);
		service.putTask(test36);
		service.putTask(test37);
		service.putTask(test38);
		service.putTask(test39);
		service.putTask(test40);
		service.putTask(test41);
		service.putTask(test42);
		service.putTask(test43);
		service.putTask(test44);
		service.putTask(test45);
	}}
